CREATE TABLE [dbo].[Course]
(
	[CId] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[CourseId] INT NOT NULL,
	[SchoolId] INT NOT NULL,
	[CourseName] INT NOT NULL,
	FOREIGN KEY(SCHOOLID) REFERENCES SCHOOL(SCHOOLID)
)
