CREATE TABLE [dbo].[Date]
(
	[DateKey] INT NOT NULL PRIMARY KEY, 
    [DD] INT NOT NULL,
	[MM] INT NOT NULL,
	[YYYY] INT NOT NULL,
	[DayOfWeek] NVARCHAR(10) NOT NULL,
	[DayNumOfWeek] INT NOT NULL,
	[DayOfYear] INT NOT NULL,
	[HalfOfYear] INT NOT NULL,
	[QuarterOfYear] INT NOT NULL
)
