CREATE TABLE [dbo].[Address]
(
	[AddressId] INT NOT NULL PRIMARY KEY IDENTITY(1000,1), 
    [StudentId] INT NOT NULL UNIQUE, 
    [Street] VARCHAR(30) NULL, 
    [City] VARCHAR(30) NULL, 
    [Province] VARCHAR(20) NULL, 
    [Country] VARCHAR(20) NULL,
    FOREIGN KEY(STUDENTID) REFERENCES STUDENT(STUDENTID)
)

