CREATE TABLE [dbo].[GradePoint]
(
	[GPId] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[StudentId] INT NOT NULL,
	[GPA] DECIMAL(18,2) NOT NULL,
	[GpaUpdated] BIT DEFAULT 0
	FOREIGN KEY(STUDENTID) REFERENCES STUDENT(STUDENTID) 
)
