CREATE PROCEDURE [dbo].[UpdateStaffRating]
AS
	SET NOCOUNT ON
	DECLARE @STAFFIDS AS TABLE (ID INT IDENTITY(1,1), STAFFID INT NOT NULL)

	INSERT INTO @STAFFIDS
	SELECT DISTINCT(STAFFID) FROM StaffTeaches

	DECLARE @CNT INT = 1;
	DECLARE @TOTALCOUNT INT = (SELECT MAX(ID) FROM @STAFFIDS)
	DECLARE @STAFFID INT = 0
	DECLARE @AVGRATING DECIMAL = 0

	WHILE @CNT <= @TOTALCOUNT
	BEGIN
		SET @STAFFID = (SELECT STAFFID FROM @STAFFIDS WHERE ID = @CNT)
		SET @AVGRATING = (SELECT AVG(Rating) FROM StaffTeaches WHERE StaffId = @STAFFID)
		UPDATE STAFF
			SET Rating = @AVGRATING
			WHERE StaffId = @STAFFID
	END

RETURN 0
